config/routes.rb
Intranet::Application.routes.draw do

  resources :jc_comments

  get "monitoring/index"
  
  get "monitoring/controlling"

  resources :images

  resources :assignments

  resources :bug_statuses

  resources :bugs

  resources :work_categories

  resources :hours do
     get :autocomplete_project_name, :on => :collection
  end

  resources :tasks
  
  resources :review_images do
    resources :jc_comments
  end
  
  resources :reviews
  resources :project_statuses

  resources :projects do
    resources :tasks
    resources :reviews do
      resources :review_images do
         resources :jc_comments
      end
    end
  end

  resources :clients

  resources :profiles

  resources :comments
  
  get 'users/show'

  devise_for :users, :path_names => { :sign_up => "register", :sign_in => 'sign_in' }

  resources :post_categories

  resources :posts do 
    resources :comments
  end
  
  match 'login' => 'users#login', :as => :login  
  
  match 'monitor' => 'monitoring#index', :as => :monitor
  
  match 'controlling' => 'monitoring#controlling', :as => :controlling
  
  get "home/index"

  root :to => 'home#index'

end

app/controllers/project_statuses_controller.rb
class ProjectStatusesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /project_statuses
  # GET /project_statuses.json
  def index
    @project_statuses = ProjectStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_statuses }
    end
  end

  # GET /project_statuses/1
  # GET /project_statuses/1.json
  def show
    @project_status = ProjectStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_status }
    end
  end

  # GET /project_statuses/new
  # GET /project_statuses/new.json
  def new
    @project_status = ProjectStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_status }
    end
  end

  # GET /project_statuses/1/edit
  def edit
    @project_status = ProjectStatus.find(params[:id])
  end

  # POST /project_statuses
  # POST /project_statuses.json
  def create
    @project_status = ProjectStatus.new(params[:project_status])

    respond_to do |format|
      if @project_status.save
        format.html { redirect_to @project_status, notice: 'Project status was successfully created.' }
        format.json { render json: @project_status, status: :created, location: @project_status }
      else
        format.html { render action: "new" }
        format.json { render json: @project_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_statuses/1
  # PUT /project_statuses/1.json
  def update
    @project_status = ProjectStatus.find(params[:id])

    respond_to do |format|
      if @project_status.update_attributes(params[:project_status])
        format.html { redirect_to @project_status, notice: 'Project status was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_statuses/1
  # DELETE /project_statuses/1.json
  def destroy
    @project_status = ProjectStatus.find(params[:id])
    @project_status.destroy

    respond_to do |format|
      format.html { redirect_to project_statuses_url }
      format.json { head :ok }
    end
  end
end

app/helpers/project_statuses_helper.rb
module ProjectStatusesHelper
end

app/views/project_statuses/_form.html.haml
= simple_form_for @project_status do |form|

  -if @project_status.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@project_status.errors.count, "error")} prohibited this #{ProjectStatus.name.titleize} from being saved:"
      %ul
        - @project_status.errors.full_messages.each do |msg|
          %li= msg  

  = form.input :name, :label => 'Name'

  .actions
    = form.button :submit

app/views/project_statuses/edit.html.haml
%h1 Editing project_status

= render 'form'

= link_to 'Show', @project_status
\|
= link_to 'Back', project_statuses_path

app/views/project_statuses/index.html.haml
%h1 Listing project_statuses

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @project_statuses.each do |project_status|
    %tr
      %td= project_status.name
      %td= link_to 'Show', project_status
      %td= link_to 'Edit', edit_project_status_path(project_status)
      %td= link_to 'Destroy', project_status, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Project status', new_project_status_path

app/views/project_statuses/new.html.haml
%h1 New project_status

= render 'form'

= link_to 'Back', project_statuses_path

app/views/project_statuses/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @project_status.name

= link_to 'Edit', edit_project_status_path(@project_status)
\|
= link_to 'Back', project_statuses_path