config/routes.rb
Intranet::Application.routes.draw do

  resources :jc_comments

  get "monitoring/index"
  
  get "monitoring/controlling"

  resources :images

  resources :assignments

  resources :bug_statuses

  resources :bugs

  resources :work_categories

  resources :hours do
     get :autocomplete_project_name, :on => :collection
  end

  resources :tasks
  
  resources :review_images do
    resources :jc_comments
  end
  
  resources :reviews
  resources :project_statuses

  resources :projects do
    resources :tasks
    resources :reviews do
      resources :review_images do
         resources :jc_comments
      end
    end
  end

  resources :clients

  resources :profiles

  resources :comments
  
  get 'users/show'

  devise_for :users, :path_names => { :sign_up => "register", :sign_in => 'sign_in' }

  resources :post_categories

  resources :posts do 
    resources :comments
  end
  
  match 'login' => 'users#login', :as => :login  
  
  match 'monitor' => 'monitoring#index', :as => :monitor
  
  match 'controlling' => 'monitoring#controlling', :as => :controlling
  
  get "home/index"

  root :to => 'home#index'

end

app/models/review_image.rb
require 'paperclip_processors/watermark'

class ReviewImage < ActiveRecord::Base
  
  validates_presence_of :review_id, :unless => :nested

  attr_accessor :nested
  
  
  belongs_to :review
  belongs_to :project

  has_many :jc_comments, :as => :commentable, :dependent => :destroy
  
  has_attached_file :photo,
                    :processors => [:watermark],
                    :styles => { 
                      :medium =>{
                          :geometry => "800x800>",
                          :watermark_path => "#{Rails.root}/public/images/watermark.png"
                        },
                      :thumb => "200x200>" 
                    }
  
end

app/controllers/review_images_controller.rb
class ReviewImagesController < LoginRequiredController
  # GET /review_images
  # GET /review_images.json
  def index
    @review_images = ReviewImage.all

    respond_to do |format|
      format.html {
        if current_user.profile.is_client?
          redirect_to root_url, :flash => { :error => "Permission denied!" }
        end
      }
      format.json { render json: @review_images }
    end
  end

  # GET /review_images/1
  # GET /review_images/1.json
  def show
    @review_image = ReviewImage.find(params[:id])
    @feedback = @review_image.jc_comments
    respond_to do |format|
      format.html {
        if current_user.profile.is_client?
          render :action => 'client_show'
        end
      }
      format.json { render json: @review_image }
    end
  end

  # GET /review_images/new
  # GET /review_images/new.json
  def new
    @review_image = ReviewImage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review_image }
    end
  end

  # GET /review_images/1/edit
  def edit
    @review_image = ReviewImage.find(params[:id])
  end

  # POST /review_images
  # POST /review_images.json
  def create
    @review_image = ReviewImage.new(params[:review_image])
    @review_image.name ="#{@review_image.project.name_number}_#{@review_image.photo_file_name}" if @review_image.name.blank?
    respond_to do |format|
      if @review_image.save
        format.html { redirect_to @review_image, notice: 'Review image was successfully created.' }
        format.json { render json: @review_image, status: :created, location: @review_image }
      else
        format.html { render action: "new" }
        format.json { render json: @review_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /review_images/1
  # PUT /review_images/1.json
  def update
    @review_image = ReviewImage.find(params[:id])

    respond_to do |format|
      if @review_image.update_attributes(params[:review_image])
        format.html { redirect_to @review_image, notice: 'Review image was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @review_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /review_images/1
  # DELETE /review_images/1.json
  def destroy
    @review_image = ReviewImage.find(params[:id])
    @review_image.destroy

    respond_to do |format|
      format.html { redirect_to review_images_url }
      format.json { head :ok }
    end
  end
end

app/helpers/review_images_helper.rb
module ReviewImagesHelper
end

app/views/review_images/_coord_form.html.erb
<div class="jc_coords">
<%= simple_form_for [@commentable, JcComment.new] do |f| %>
	<%= f.hidden_field :x1 %>
	<%= f.hidden_field :x2 %>
	<%= f.hidden_field :y1 %>
	<%= f.hidden_field :y2 %>
	<%= f.hidden_field :h %>
	<%= f.hidden_field :w %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.hidden_field :commentable_id, :value => image_id %>
	<%= f.hidden_field :commentable_type, :value => 'ReviewImage' %>
	<%= f.input :content, :rows => 5,  :value => 'add feedback...', :onfocus => 'this.select()'  %>
	<%= f.submit "send", :class => 'btn btn-success' %>
<% end %>
</div>

app/views/review_images/_form.html.haml
= simple_form_for @review_image do |form|

  -if @review_image.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@review_image.errors.count, "error")} prohibited this #{ReviewImage.name.titleize} from being saved:"
      %ul
        - @review_image.errors.full_messages.each do |msg|
          %li= msg  

  = form.input :review_id, :label => 'Review'
  = form.input :name, :label => 'Name'
  = form.input :project_id, :label => 'Project'

.actions
  = form.button :submit

app/views/review_images/client_show.html.haml
.row
  .span12
    .review_image
      %h2= "#{@review_image.review.name} - #{@review_image.name}"
      .project= "Project: #{link_to @review_image.review.project.name_number, @review_image.review.project}".html_safe
      %br
      %p.alert.alert-info= "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

.row
  .span8
    .review_image_detail
      .image= image_tag @review_image.photo.url(:medium), :id => "review_image"
      #comments
        - @feedback.with_position.each do |fb|
          .feedback{ :style => "position: absolute; left: #{fb.x1}px; top: #{fb.y1}px; width: #{fb.w}px; height: #{fb.h}px" }= fb.content

    .comments_area
      - @feedback.with_position.each do |fb|
        .user_feedback
          %span.user= fb.user.profile.name
          %span.date= " wrote #{time_ago_in_words(fb.created_at)} ago: "
          %span.message= fb.content

      
    %br.clear
  .span4
    .preview_window= image_tag @review_image.photo.url(:medium), :id => "preview"
    .coords= render :partial => 'coord_form', :locals => {:image_id => @review_image.id}


.backlink= link_to "Go Back", review_path(@review_image.review), :title => 'Back to Project', :class => 'btn' 
%br
.debug= debug @feedback
%br
%br
  

app/views/review_images/edit.html.haml
%h1 Editing review_image

= render 'form'

= link_to 'Show', @review_image
\|
= link_to 'Back', review_images_path

app/views/review_images/index.html.haml
%h1 Listing review_images

%table
  %tr
    %th Review
    %th Name
    %th Project
    %th
    %th
    %th

  - @review_images.each do |review_image|
    %tr
      %td= review_image.review_id
      %td= review_image.name
      %td= review_image.project_id
      %td= link_to 'Show', review_image
      %td= link_to 'Edit', edit_review_image_path(review_image)
      %td= link_to 'Destroy', review_image, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Review image', new_project_review_image_path

app/views/review_images/new.html.haml
%h1 New review_image

= render 'form'

= link_to 'Back', review_images_path

app/views/review_images/show.html.haml
#scrolldiv
  .review_image_detail
     .image= image_tag (@review_image.photo.url(:medium))
     .comments
       = @feedback.with_position.each do |fb|
         .feedback{ :style => "position: absolute; left: #{fb.x1}px; top: #{y1}px; width: #{fb.w}px" }= fb.content
  


= link_to 'Back', review_path(@review_image.review)

app/views/review_images/show.js.erb
alert('buh');