config/routes.rb
Intranet::Application.routes.draw do

  resources :jc_comments

  get "monitoring/index"
  
  get "monitoring/controlling"

  resources :images

  resources :assignments

  resources :bug_statuses

  resources :bugs

  resources :work_categories

  resources :hours do
     get :autocomplete_project_name, :on => :collection
  end

  resources :tasks
  
  resources :review_images do
    resources :jc_comments
  end
  
  resources :reviews
  resources :project_statuses

  resources :projects do
    resources :tasks
    resources :reviews do
      resources :review_images do
         resources :jc_comments
      end
    end
  end

  resources :clients

  resources :profiles

  resources :comments
  
  get 'users/show'

  devise_for :users, :path_names => { :sign_up => "register", :sign_in => 'sign_in' }

  resources :post_categories

  resources :posts do 
    resources :comments
  end
  
  match 'login' => 'users#login', :as => :login  
  
  match 'monitor' => 'monitoring#index', :as => :monitor
  
  match 'controlling' => 'monitoring#controlling', :as => :controlling
  
  get "home/index"

  root :to => 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  
  acts_as_birthday :deadline
  
  validates_presence_of :nr
  validates_presence_of :client_id
  validates_presence_of :name
  validates_uniqueness_of :nr
  
  belongs_to :client
  belongs_to :project_status
  
  has_many :assignments
  has_many :tasks, :dependent => :destroy
  has_many :profiles, :through => :assignments, :class_name => "Profile", :source => :profile  
  
  has_many :hours
  
  has_many :reviews
  
  #attr_accessible :nr, :name, :client_id, :project_status_id, :hidden, :active, :description, :tasks_attributes, :profiles_attributes, :profile_tokens
  
  attr_reader :name_number, :profile_tokens
  
  scope :active, where(:active => '1')
  scope :visible, where(:hidden => '0')
  scope :design, where(:web => '0')
  scope :web, where(:web => '1')
  scope :in_progress, where(:project_status_id => '1')
  scope :future, :conditions => [' deadline >= ? ', Date.today ]
  scope :with_user, lambda { |user_id| joins(:assignments).where(:user_id => user_id) }
  scope :with_status, lambda { |status_id| where( :project_status_id => status_id ).order(:deadline) }
  scope :continous, where(:project_status_id => '2')
  scope :external, where(:internal => false)
  scope :internal,  where(:internal => true)
  scope :no_absence, :conditions => ['nr <> ? ', '00' ] # 189 = id of Project 00 - Absence
  scope :scheduled, where(:project_status_id => '4')
  scope :feedback_enabled, where(:feedback_enabled => true)
  
  accepts_nested_attributes_for :tasks, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :reviews, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true 
  
  def self.search(search)  
    if search  
      where('name LIKE ? OR nr LIKE ?', "%#{search}%", "%#{search}%")  
    else  
      scoped  
    end  
  end
  
  def self.next_deadlines(profile)
    profile.projects.in_progress.order(:deadline)
  end

  def self.upcoming_projects(profile)
    profile.projects.scheduled.order(:deadline)
  end
  
  def self.continous_projects(profile)
    profile.projects.continous.order(:nr)
  end
  
  # returns all open / running reviews for this project
  def open_reviews
    self.reviews.running
  end
  
  # returns all closed reviews
  def closed_reviews
    self.reviews.closed
  end
  
  def name_number
    "#{self.nr} - #{self.name[0..24]}"
  end
  
  def sum_plan_hours
    tasks.to_a.sum { |task| task.plan_hours.nil? ? 0 :  task.plan_hours}
  end
  
  # helper function for jQuery tokenized input
  def profile_tokens=(ids)
    self.profile_ids = ids.split(',')
  end
  
  # gives total hours of project or, if a user is given, the total hours of this user on the project
  def total_hours(user=nil, extra = false)
    if user
      hours = self.hours.where(:user_id => user)
    else
      hours = self.hours
    end
    if extra
      hours = hours.where(:extra => true)
    end
    hours.to_a.sum { |hour| hour.amount }
  end
  
  # return an array of hours that a given user booked on this project
  def user_hours(user)
    hours = self.hours.where(:user_id => user).order(:date)
  end
  
  # returns a list of all user ids that booked hours on this project
  def project_users
    user_list = []
    self.hours.each do |h|
      user_list << h.user_id
    end
    user_list.uniq
  end
  
  
  protected
  
  def ensure_no_hours
    if self.hours.count > 0
      return false
    else
      return true
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < LoginRequiredController
  load_and_authorize_resource

  
  # GET /projects
  # GET /projects.json
  def index
    if current_user.profile.is_client?
      @projects = Project.feedback_enabled.where(:client_id => current_user.profile.client_id).order(sort_column + ' ' + sort_direction).page(params[:page])
      render :action => 'client_index'
    else
      @projects = Project.search(params[:search]).order(sort_column + ' ' + sort_direction).page(params[:page])
    end
    
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @project.tasks.order(:name)
    respond_to do |format|
      format.html {
        if current_user.profile.is_client?
          # dirty hack---- needs to be in PROJECT
          @project_leader = Profile.find(@project.reviews.first.project_leader_id)
          render :action => 'client_show'
        end
      }
      format.json { render json: @project }
      format.xls
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    propose_nr = Integer(Project.order("nr desc").first.nr) + 1
    @project = Project.new(:nr => propose_nr, :active => true, :deadline => Date.today + 2.weeks, :project_status_id => 11)
    @project.tasks.new(:name => "Project Mgmt", :description => "")
    @project.tasks.new(:name => "Pre-P", :description => "Moodboards | Examining project data, plans, briefing, etc.")
    @project.tasks.new(:name => "Web", :description => "Flatfinder/Boligvelger (eve-Estate)  |  CMS/Website (eve-Publisher)  |  Landingpage")
    @project.tasks.new(:name => "Undividable 3D work for exteriors", :description => "Modeling/texturing of buildings and their surroundings. Populating/detailing with plants, outdoor furniture, traffic, etc.")
    @project.tasks.new(:name => "Undividable 3D work for interiors", :description => "Modeling/texturing of X (apartment) rooms. Setting up furniture, accessories, decoration according to moodboards.")
    @project.tasks.new(:name => "#{propose_nr}-01_e", :description => "Scene setup, lighting and detail adjustments, rendering with subsequent post-production/compositing.")
    @project.tasks.order(:name)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
  
  def sort_column  
    controller_name.classify.constantize.column_names.include?(params[:sort]) ? params[:sort] : "nr"  
  end
  
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/___old_form.html.haml
= simple_nested_form_for @project do |form|

  -if @project.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this #{Project.name.titleize} from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg  

  = form.input :nr, :label => 'Nr'
  = form.input :name, :label => 'Name'
  = form.association :client, :collection => Client.all(:order => 'name'), :prompt => "Choose a Client"
  = form.input :description, :label => 'Description'
  = form.input :active, :label => 'Active'
  = form.input :hidden, :label => 'Hidden'
  .task_fields
    = form.fields_for :tasks do |task_form|
      = task_form.input :name 
      = task_form.input :description 
      = task_form.input :deadline
      = task_form.link_to_remove "Remove this task"
      %p= form.link_to_add "Add a task", :tasks

  .actions
    = form.button :submit

app/views/projects/__projects.html.haml
%table.pretty
  %tr
    %th= sortable "nr"
    %th= sortable "name"
    %th= sortable "client"
    %th Description
    %th= sortable "status"
    %th
    %th
    %th
  
  - @projects.each do |project|
    %tr
      %td= link_to project.nr, project, :class => "blue"
      %td= link_to project.name, project, :class => "blue"
      %td= link_to project.client.name, project.client, :class => 'blue'
      %td= markdown(project.description)[0..29] + "..."
      %td= project.project_status.name
      %td= link_to image_tag('zoom_in.png'), project, :title => 'details'
      %td= link_to image_tag('edit.png'), edit_project_path(project), :title => 'edit'
      %td= link_to image_tag('delete.png'), project, :title => 'delete', :confirm => 'Are you sure?', :method => :delete

app/views/projects/_client_projects.html.haml
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th= sortable "nr", "Project Nr."
      %th= sortable "name"
      %th= sortable "client_id", "Client"
      %th= sortable "deadline"
      %th= sortable "project_status_id", "Status"
      %th= sortable "web_preoject", "Web"
      %th

  %tbody
  - @projects.each do |project|
    %tr
      %td
        %span.badge.badge-info= project.nr
      %td= link_to project.name, project, :class => "blue"
      %td= project.client.name
      %td= project.deadline.strftime('%d.%m.%y')
      %td= project.project_status.name
      %td= project.web? ? "&#x2713;".html_safe : ""
      %td= link_to ((content_tag(:i, '', :class => 'icon-info-sign icon-white')) + ' Details').html_safe, project, :title => 'details', :class => 'btn btn-info'

app/views/projects/_form.html.erb
<%= tinymce_assets %>
<div id="scrolldiv">
<%= simple_nested_form_for @project do |form| %>

  <% if @project.errors.any? %>
    <div id="errorExplanation">
      <h2><%="#{pluralize(@project.errors.count, "error")} prohibited this #{Project.name.titleize} from being saved:"%></h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg  %></li>
         <% end %>
      </ul>
  <% end %>

  <%= form.input :nr, :label => 'Nr' %>
  <%= form.input :name, :label => 'Name' %>
  <%= form.input :internal, :label => 'Inhouse ?' %>
  <%= form.association :client, :collection => Client.all(:order => 'name'), :prompt => "Choose a Client" %>
  <%= form.association :project_status, :collection => ProjectStatus.all(:order => 'id'), :prompt => false %>
  <%= form.input :deadline %>
  <%= form.input :description, :label => 'Description',  :input_html => {:class => "tinymce", :rows => 40, :cols => 40, 
:value =>  @project.new_record? ? "		<p><strong>Output</strong></p>
		<p>e:&nbsp;&nbsp; | &nbsp; i: (X rooms)&nbsp;&nbsp; | &nbsp; a:</p>
		<p>(web?)</p>
		<p>(photo shoot?)</p>
		<p>(+ 1 free close-up?)</p>
		<hr />
		<p><strong>Project Description</strong></p>
		<p>&nbsp;</p>
		<p>(Continuation/Update of 000?)</p>
		<hr />
		<p><strong>Deadlines</strong></p>
		<ul>
		<li>Whiteviews:</li>
		<li>Preview 1:</li>
		<li>Preview 2:</li>
		</ul>
		<hr />
		<p><strong>Client Info</strong></p>
		<ol>
		<li><em>Offer no</em>:</li>
		<li><em>Billing Address</em>:</li>
		<li><em>Client project no</em>:</li>
		<li><em>Contact Person</em>s:</li>
		<li><em>Invoice no</em>:</li>
		</ol>".html_safe : @project.description } %>
	<div class="admin_fields">
  <%= form.input :web, :label => 'Web Project?', :hint => 'project not relevant for 3D artists' %>
  <%= form.input :locked, :label => 'Lock Project', :hint => 'Hours cannot be changed anymore - no new bookings on this project' %>
  <%= form.input :feedback_enabled, :label => 'Feedback Enabled?', :hint => 'If checked, project is available for client feedback.' %>
  </div>
	<%= form.input :profile_tokens, :label => 'Involved People',  :input_html => { :data => { :pre => @project.profiles.map(&:attributes).to_json }} %>
	<br class="clear"/>
  <div class="task_fields">
		<h4>Tasks</h4>
    <%= form.fields_for :tasks do |task_form| %>
      <%= task_form.input :name %>
      <%= task_form.input :description  %>
      <%= task_form.input :plan_hours %>
      <%= task_form.link_to_remove "Remove this task" %>
     <% end %>
		<p><%= form.link_to_add "Add a task", :tasks %></p>
  </div>
  <div class="actions project_submit_button">
    <%= form.button :submit %>
  </div>
<% end %>
</div>
<%= tinymce %>

app/views/projects/_form.html.haml
= simple_nested_form_for @project do |form|

  -if @project.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this #{Project.name.titleize} from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg  

  = form.input :nr, :label => 'Nr'
  = form.input :name, :label => 'Name'
  = form.association :client, :collection => Client.all(:order => 'name'), :prompt => "Choose a Client"
  = form.input :description, :label => 'Description'
  = form.input :active, :label => 'Active'
  = form.input :hidden, :label => 'Hidden'
  .task_fields
    = form.fields_for :tasks do |task_form|
      = task_form.input :name 
      = task_form.input :description 
      = task_form.input :deadline
      = task_form.link_to_remove "Remove this task"
      %p= form.link_to_add "Add a task", :tasks

  .actions
    = form.button :submit

app/views/projects/_projects.html.haml
%table.pretty
  %tr
    %th= sortable "nr"
    %th= sortable "name"
    %th= sortable "client_id", "Client"
    %th= sortable "deadline"
    %th= sortable "project_status_id", "Status"
    %th= sortable "web", "Web"
    %th
    %th
    %th
  
  - @projects.each do |project|
    %tr
      %td= link_to project.nr, project, :class => "blue"
      %td= link_to project.name, project, :class => "blue"
      %td= link_to project.client.name, project.client, :class => 'blue'
      %td= project.deadline.strftime('%d.%m.%y')
      %td= project.project_status.name
      %td= project.web? ? "&#x2713;".html_safe : ""
      %td= link_to image_tag('zoom_in.png'), project, :title => 'details'
      -if current_user.admin? || current_user.project_manager?
        %td= link_to image_tag('edit.png'), edit_project_path(project), :title => 'edit'
        %td= link_to image_tag('delete.png'), project, :title => 'delete', :confirm => 'Are you sure?', :method => :delete

app/views/projects/client_index.html.haml
%h1 Your Projects


#projects= render :partial => 'client_projects'


.paginator= paginate @projects
  					
  
%br

app/views/projects/client_show.html.haml
%h1= "#{@project.nr} - #{@project.name}"

.row
  .span8
    %p= "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  
  .span4
    %table.table.table-striped.table-bordered
      %tr
        %td Contact Person
        %td= link_to @project_leader.user.email, "mailto:#{@project_leader.user.email}"
      %tr
        %td Rufnummer für Rückfragen
        %td= @project_leader.phone
      %tr
        %td Estimated Deadline
        %td= @project.deadline.strftime('%d.%m.%Y')


.row
  .span12
    %h2 Reviews
    %p= "There are #{@project.open_reviews.count} running reviews and #{@project.closed_reviews.count} closed reviews for this project"
    %table.table.table-striped.table-bordered
      %tr
        %th #
        %th name
        %th status
        %th date opened
        %th date closed
        %th nr of images
        %th nr of comments
        %th details
      -@project.reviews.each_with_index do |pr, i|
        %tr{:class => ("inactive" if pr.closed?)}
          %td= i
          %td= link_to pr.name, pr
          %td= pr.closed? ? "closed" : "running"
          %td= pr.date_opened.strftime('%d.%m.%Y %H:%M')
          %td= pr.date_closed.strftime('%d.%m.%Y %H:%M')
          %td= pr.review_images.count
          %td= pr.comments_count
          - if pr.closed?
            %td= link_to ((content_tag(:i, '', :class => 'icon-info-sign icon-white')) + '  See Feedback').html_safe, pr, :title => 'Show Details', :class => 'btn btn-info'
          - else
            %td= link_to ((content_tag(:i, '', :class => 'icon-eye-open icon-white')) + '  Add Feedback').html_safe, pr, :title => 'Add Feedback', :class => 'btn btn-success'
         

         

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

.edit_links
  = link_to 'Update', "#", :id => "secondary_update_link"
  \|
  = link_to 'Show', @project
  \|
  = link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Projects

#scrolldiv
  .content_window.fullsize
    .headline
      .searchform
        = form_tag projects_path, :method => :get, :id => 'projects_search'
        %p
          = hidden_field_tag :direction, params[:direction]
          = hidden_field_tag :sort, params[:sort] 
          = text_field_tag :search, params[:search], :class => "table_search", :onfocus => 'this.select();'
          = submit_tag "Search", :name => nil
      %br.clear
    .inner
      #projects= render :partial => 'projects'


      .paginator= paginate @projects
  					
    .edit_links
      = link_to 'New Project', new_project_path, :class => 'new_object_link'
  
%br

app/views/projects/index.js.erb
$('#projects').html('<%= escape_javascript (render(:partial => "projects")) %>');  

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
-present @project do |project_presenter|

	%h1.project_h1
		%span.projectnr= project_presenter.project_nr
		%span.clientname= link_to project_presenter.client, @project.client
		%span.projectname= project_presenter.title
		%span.locked= image_tag('locked-icon.png', :width => 50, :title => 'Project is locked.') if @project.locked?

	#scrolldiv
		#project.content_window.fullsize
			.header= link_to "Project Overview", "javascript:void(0)", :class => 'open', :title => "open / close"
  		
			.inner
				.column
					.subtitle Description
					.subcontent
						.description= project_presenter.description.html_safe
  	
				
				.column.middle_col
					.subtitle Involved People
					.subcontent
						.description= project_presenter.people
					%br
					%br
					.subtitle Status
					.subcontent
						.description= project_presenter.status
					%br
					%br
					.subtitle Deadline
					.subcontent
						.description= @project.deadline.strftime('%d.%m.%y')
					%br
					%br
					.subtitle Total (plan | spent)
					.subcontent
						.description= "#{@project.sum_plan_hours} | #{@project.total_hours}"
				
				.column.tasks_col
					.subtitle Tasks
					.subcontent
						.tasks= project_presenter.tasks
				
				%br.clear
				.edit_links
					-if can? :update, @project
						= link_to 'Edit', edit_project_path(@project)
						\|
					= link_to 'Back', projects_path			
				
					
		#project_statistics.content_window.fullsize
			.header= link_to "Project Details", "javascript:void(0)", :class => 'open', :title => "open / close"
		
			.inner
				.column
					.dl_xls= link_to "Download xls", url_for(:format => 'xls')
					.hour_details= project_presenter.hour_details
			

			%br.clear
  
	#reviews.content_window.fullsize
		.header= link_to "Reviews", "javascript:void(0)", :class => 'open', :title => "open / close"
		.inner
			.edit_links
				- if @project.feedback_enabled?
					%span= link_to 'new review round', new_review_path(:project_id => @project.id), :class => 'new_object_link'
				- else
					%span= "Project Feedback not enabled."
			  
			.column
				.hour_details= project_presenter.reviews
	
			%br.clear
	         



    	
    	

app/views/projects/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/>
   <Borders/>
   <Font ss:FontName="Verdana"/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  <Style ss:ID="s21">
   <Font ss:FontName="Verdana" ss:Bold="1"/>
  </Style>
 </Styles>
  <Worksheet ss:Name="Sheet1">
    <Table>
	   <Row>
	    <Cell ss:Index="2"><Data ss:Type="String">Detail Infos for <%= @project.name_number %></Data></Cell>
	   </Row>
	   <Row ss:Index="3" ss:StyleID="s21">
        <Cell><Data ss:Type="String">Employee</Data></Cell>
        <Cell><Data ss:Type="String">Date</Data></Cell>
        <Cell><Data ss:Type="String">Hours</Data></Cell>
        <Cell><Data ss:Type="String">Extra</Data></Cell>
        <Cell><Data ss:Type="String">Desciption</Data></Cell>
				<Cell><Data ss:Type="String">Task</Data></Cell>
      </Row>
    <% @project.hours.each do |h| %>
    	  <Row>
    	    <Cell><Data ss:Type="String"><%= h.user.username %></Data></Cell>
    	    <Cell><Data ss:Type="String"><%= h.date.strftime('%d.%m.%Y') %></Data></Cell>
    	    <Cell><Data ss:Type="Number"><%= h.amount %></Data></Cell>
    	    <Cell><Data ss:Type="String"><%= h.extra? ? 'yes' : 'no' %></Data></Cell>
    	    <Cell><Data ss:Type="String"><%= h.description %></Data></Cell>
    	    <Cell><Data ss:Type="String"><%= h.task.nil? ? '--' : h.task.name %></Data></Cell>
    	  </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>