config/routes.rb
Intranet::Application.routes.draw do

  resources :jc_comments

  get "monitoring/index"
  
  get "monitoring/controlling"

  resources :images

  resources :assignments

  resources :bug_statuses

  resources :bugs

  resources :work_categories

  resources :hours do
     get :autocomplete_project_name, :on => :collection
  end

  resources :tasks
  
  resources :review_images do
    resources :jc_comments
  end
  
  resources :reviews
  resources :project_statuses

  resources :projects do
    resources :tasks
    resources :reviews do
      resources :review_images do
         resources :jc_comments
      end
    end
  end

  resources :clients

  resources :profiles

  resources :comments
  
  get 'users/show'

  devise_for :users, :path_names => { :sign_up => "register", :sign_in => 'sign_in' }

  resources :post_categories

  resources :posts do 
    resources :comments
  end
  
  match 'login' => 'users#login', :as => :login  
  
  match 'monitor' => 'monitoring#index', :as => :monitor
  
  match 'controlling' => 'monitoring#controlling', :as => :controlling
  
  get "home/index"

  root :to => 'home#index'

end

app/models/work_category.rb
class WorkCategory < ActiveRecord::Base
  has_many :hours
end

app/controllers/work_categories_controller.rb
class WorkCategoriesController < ApplicationController
  # GET /work_categories
  # GET /work_categories.json
  def index
    @work_categories = WorkCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @work_categories }
    end
  end

  # GET /work_categories/1
  # GET /work_categories/1.json
  def show
    @work_category = WorkCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work_category }
    end
  end

  # GET /work_categories/new
  # GET /work_categories/new.json
  def new
    @work_category = WorkCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work_category }
    end
  end

  # GET /work_categories/1/edit
  def edit
    @work_category = WorkCategory.find(params[:id])
  end

  # POST /work_categories
  # POST /work_categories.json
  def create
    @work_category = WorkCategory.new(params[:work_category])

    respond_to do |format|
      if @work_category.save
        format.html { redirect_to @work_category, notice: 'Work category was successfully created.' }
        format.json { render json: @work_category, status: :created, location: @work_category }
      else
        format.html { render action: "new" }
        format.json { render json: @work_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /work_categories/1
  # PUT /work_categories/1.json
  def update
    @work_category = WorkCategory.find(params[:id])

    respond_to do |format|
      if @work_category.update_attributes(params[:work_category])
        format.html { redirect_to @work_category, notice: 'Work category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @work_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_categories/1
  # DELETE /work_categories/1.json
  def destroy
    @work_category = WorkCategory.find(params[:id])
    @work_category.destroy

    respond_to do |format|
      format.html { redirect_to work_categories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/work_categories_helper.rb
module WorkCategoriesHelper
end

app/views/work_categories/_form.html.haml
= simple_form_for @work_category do |form|

  -if @work_category.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@work_category.errors.count, "error")} prohibited this #{WorkCategory.name.titleize} from being saved:"
      %ul
        - @work_category.errors.full_messages.each do |msg|
          %li= msg  

  = form.input :name, :label => 'Name'

  .actions
    = form.button :submit

app/views/work_categories/edit.html.haml
%h1 Editing work_category

= render 'form'

= link_to 'Show', @work_category
\|
= link_to 'Back', work_categories_path

app/views/work_categories/index.html.haml
%h1 Listing work_categories

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @work_categories.each do |work_category|
    %tr
      %td= work_category.name
      %td= link_to 'Show', work_category
      %td= link_to 'Edit', edit_work_category_path(work_category)
      %td= link_to 'Destroy', work_category, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Work category', new_work_category_path

app/views/work_categories/new.html.haml
%h1 New work_category

= render 'form'

= link_to 'Back', work_categories_path

app/views/work_categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @work_category.name

= link_to 'Edit', edit_work_category_path(@work_category)
\|
= link_to 'Back', work_categories_path